apiVersion: apps/v1
kind: Deployment
metadata:
  name: was-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
      - name: was
        image: gcr.io/kdt1-finalproject/petclinic:20250711012642
        ports:
          - containerPort: 8080
