apiVersion: apps/v1            
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: gcr.io/kdt1-finalproject/petclinic-web:1
        ports:
          - containerPort: 80
